/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IGlobalConst, IGlobalConstInterface } from "../IGlobalConst";

const _abi = [
  {
    inputs: [],
    name: "fluenceToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "minDepositedEpoches",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "minRematchingEpoches",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IGlobalConst__factory {
  static readonly abi = _abi;
  static createInterface(): IGlobalConstInterface {
    return new Interface(_abi) as IGlobalConstInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGlobalConst {
    return new Contract(address, _abi, runner) as unknown as IGlobalConst;
  }
}
