/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IController__factory } from "./IController__factory";
export { IControllerInitializable__factory } from "./IControllerInitializable__factory";
